services:
  auto-cv:
    image: ghcr.io/matthieuev/auto-cv/auto-cv:latest
    environment:
      POCKETBASE_CLIENT_URL: <YOUR_POCKETBASE_CLIENT_URL>
      POCKETBASE_EMAIL: <YOUR_POCKETBASE_EMAIL>
      POCKETBASE_PASSWORD: <YOUR_POCKETBASE_PASSWORD>

      POCKETBASE_EN_PDF_ID: <YOUR_POCKETBASE_EN_PDF_ID>
      POCKETBASE_FR_PDF_ID: <YOUR_POCKETBASE_FR_PDF_ID>